version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_DB=math_game
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - SECRET_KEY=your_secret_key
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./logs:/mnt/logs

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=math_game
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d math_game"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: