name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Format code with black
        run: |
          
          find . -type f -name "*.py" | xargs black   
        
          

      - name: Lint with pylint
        run: |
          
          find . -type f -name "*.py" | xargs pylint



      - name: Run tests with pytest
        run: |
          
          pytest test_app.py

      - name: Clean up
        run: |
          echo "Clean up handled by GitHub Actions"
