name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t myapp .

    - name: Run tests
      run: docker run myapp python -m unittest test_app.py

    - name: Run pylint
      run: docker run myapp pylint app.py
      
    - name: run security scan
      run: docker run myapp bandit -r . -ll
      
        