name: Trigger auto deployment for mathgamecontainer

on:
  push:
    branches: 
      - main
    paths:
      - '**'
      - '.github/workflows/mathgamecontainer-AutoDeployTrigger-7f8459cf-a973-4125-b46a-7d9d709e244c.yml'

  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.MATHGAMECONTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MATHGAMECONTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MATHGAMECONTAINER_AZURE_SUBSCRIPTION_ID }}

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.MATHGAMECONTAINER_REGISTRY_SERVER }}
          username: ${{ secrets.MATHGAMECONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.MATHGAMECONTAINER_REGISTRY_PASSWORD }}

      - name: Build and push web container image to registry
        run: |
          docker build -t ${{ secrets.MATHGAMECONTAINER_REGISTRY_SERVER }}/mathgamecontainer:${{ github.sha }} .
          docker push ${{ secrets.MATHGAMECONTAINER_REGISTRY_SERVER }}/mathgamecontainer:${{ github.sha }}

      - name: Build and push db container image to registry
        run: |
          docker pull postgres:13
          docker tag postgres:13 ${{ secrets.MATHGAMECONTAINER_REGISTRY_SERVER }}/mathgamedb:${{ github.sha }}
          docker push ${{ secrets.MATHGAMECONTAINER_REGISTRY_SERVER }}/mathgamedb:${{ github.sha }}

      - name: Deploy DB Container to Azure
        uses: azure/container-apps-deploy-action@v2
        with:
          registryUrl: ${{ secrets.MATHGAMECONTAINER_REGISTRY_SERVER }}
          registryUsername: ${{ secrets.MATHGAMECONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MATHGAMECONTAINER_REGISTRY_PASSWORD }}
          containerAppName: mathgame-db
          resourceGroup: mathgameresource
          imageToDeploy: ${{ secrets.MATHGAMECONTAINER_REGISTRY_SERVER }}/mathgamedb:${{ github.sha }}

      - name: Deploy Web App Container to Azure
        uses: azure/container-apps-deploy-action@v2
        with:
          registryUrl: ${{ secrets.MATHGAMECONTAINER_REGISTRY_SERVER }}
          registryUsername: ${{ secrets.MATHGAMECONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MATHGAMECONTAINER_REGISTRY_PASSWORD }}
          containerAppName: mathgame-web
          resourceGroup: mathgameresource
          imageToDeploy: ${{ secrets.MATHGAMECONTAINER_REGISTRY_SERVER }}/mathgamecontainer:${{ github.sha }}
          environmentVariables: |
            POSTGRES_DB=math_game
            POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_HOST=mathgame-db
            POSTGRES_PORT=5432
            SECRET_KEY=${{ secrets.SECRET_KEY }}

      - name: Set Volume Mount for Web App
        run: |
          az containerapp update -n mathgame-web -g mathgameresource --set \
          configuration.volumes='[{"name":"mathgamevolumemount","storageType":"AzureFile","azureFile":{"shareName":"${{ secrets.FILE_SHARE_NAME }}","storageAccountName":"${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}","storageAccountKey":"${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}"}}]' \
          configuration.volumeMounts='[{"mountPath":"/mnt/logs","volumeName":"mathgamevolumemount"}]'
