name: Deploy to Azure Container Apps

on:
  push:
    branches: [ main, fix-db-yaml-v2 ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validate Docker Compose file
        run: docker compose config

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.MATHGAMECONTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MATHGAMECONTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MATHGAMECONTAINER_AZURE_SUBSCRIPTION_ID }}

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.MATHGAMECONTAINER_REGISTRY_SERVER }}
          username: ${{ secrets.MATHGAMECONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.MATHGAMECONTAINER_REGISTRY_PASSWORD }}

      - name: Build and push Single Container image
        run: |
          docker compose build single
          docker tag mydockerhubusername/math-game:latest ${{ secrets.MATHGAMECONTAINER_REGISTRY_SERVER }}/mathgame-single:${{ github.sha }}
          docker push ${{ secrets.MATHGAMECONTAINER_REGISTRY_SERVER }}/mathgame-single:${{ github.sha }}

      - name: Deploy Single Container App
        run: |
          az containerapp create \
            --name mathgame-single \
            --resource-group mathgameresource \
            --image ${{ secrets.MATHGAMECONTAINER_REGISTRY_SERVER }}/mathgame-single:${{ github.sha }} \
            --environment mathgame-db-env \
            --registry-server ${{ secrets.MATHGAMECONTAINER_REGISTRY_SERVER }} \
            --registry-username ${{ secrets.MATHGAMECONTAINER_REGISTRY_USERNAME }} \
            --registry-password ${{ secrets.MATHGAMECONTAINER_REGISTRY_PASSWORD }} \
            --env-vars "SECRET_KEY=${{ secrets.SECRET_KEY }}" \
            --cpu 1.0 --memory 2.0Gi \
            --min-replicas 1 --max-replicas 3 \
            --target-port 8080 \
            --ingress external \
            --revision-suffix "v${{ github.run_id }}" \
            --set "template.containers[0].probes=[{\"type\":\"tcp\",\"tcpSocket\":{\"port\":8080},\"initialDelaySeconds\":20,\"periodSeconds\":10,\"timeoutSeconds\":5,\"failureThreshold\":3}]" \
          || echo "Container app exists, updating..." && \
          az containerapp update \
            --name mathgame-single \
            --resource-group mathgameresource \
            --image ${{ secrets.MATHGAMECONTAINER_REGISTRY_SERVER }}/mathgame-single:${{ github.sha }} \
            --set-env-vars "SECRET_KEY=${{ secrets.SECRET_KEY }}" \
            --revision-suffix "v${{ github.run_id }}" \
            --set "template.containers[0].probes=[{\"type\":\"tcp\",\"tcpSocket\":{\"port\":8080},\"initialDelaySeconds\":20,\"periodSeconds\":10,\"timeoutSeconds\":5,\"failureThreshold\":3}]"

      - name: Check Container Logs
        run: |
          sleep 90
          az containerapp logs show --name mathgame-single --resource-group mathgameresource --tail 200 || echo "Failed to retrieve logs, continuing..."